deps:
pip install -r requirements.txt; \
pip install -r text_requirements.txt
lint:
flake8 hello_world test
run:
python main.py
test
PYTHONPATH=. py.test --verbose -s

USERNAME=wsbtester1  
TAG=$(USERNAME)/hello-world-printer  

docker_push: docker_build  
@docker login --username $(USERNAME) --password $${DOCKER_PASSWORD}; \  
docker tag hello-world-printer $(TAG); \  
docker push $(TAG); \  
docker logout;  